# DO NOT USE THIS FILE AS IT IS.

# Insert some lines below to appropriate location of
# $(srctree)/security/Makefile.

# Lines just before and after the line to be inserted
# are printed in comment format.


# subdir-$(CONFIG_SECURITY_LOADPIN)	+= loadpin
subdir-$(CONFIG_SECURITY_WHITEEGRET)	+= whiteegret


# obj-$(CONFIG_SECURITY_LOADPIN)		+= loadpin/
obj-$(CONFIG_SECURITY_WHITEEGRET)	+= whiteegret/
# obj-$(CONFIG_CGROUP_DEVICE)		+= device_cgroup.o
