# DO NOT USE THIS FILE AS IT IS.

# Insert some lines below to appropriate location of
# $(srctree)/drivers/Makefile.

# Lines just before and after the line to be inserted
# are printed in comment format.


# obj-$(CONFIG_TEE)		+= tee/
obj-$(CONFIG_SECURITY)		+= security/
